stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - echo "Building...."
    - shopt -s expand_aliases
    - alias python='/usr/bin/python3'
    - python --version
    - python -m venv flask_app
    - pip install -r requirements.txt


test:
  stage: test
  script:
    - echo "Testing..."
    - python -m pytest

deploy:
  stage: deploy
  script:
    - echo "Deploying..."
    - python --version
    - flask run
