stages:
  - build
  - test
  - deploy

build:
  stage: build
  image: python:3.8
  script: 
    - echo "Building..."
    - pip --version
    - pip install -r requirements.txt
  
test:
  stage: test
  image: python:3.8
  script:
    - echo "Testing..."
    - pip install pytest
    - python -m pytest

deploy:
  stage: deploy
  image: python:3.8
  script:
    - echo "Deploying..."
