stages:
  - build
  - test
  - deploy

image: python:3.8
  pull_policy: if-not-present

build:
  stage: build
  script:
    - echo "Building...."
    - pip3 --version
    - pip3 install -r requirements.txt
    - pip3 list

test:
  stage: test
  script:
    - echo "Testing..."
    - pip3 list
    - python3 -m pytest

deploy:
  stage: deploy
  script:
    - echo "Deploying..."
    - flask run --port 5000
