default:
  image: python:3.8

build:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"

test:
  stage: test
  script:
    - echo "This job tests something"

deploy:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."