variables:
  HEROKU_API_KEY: $heroku_api_key

before_script:
  - python3 -m venv flask_app
  - . flask_app/bin/activate

stages:
  - build
  - test
  - deploy_VM
  - deploy_heroku

cache:
  paths:
    - flask_app/

build:
  image: gitlab.informatik.uni-bremen.de:5005/hoeffner/pandoc-python-docker:latest
  services:
    - docker:dind
  stage: build
  script:
    - echo "Building...."
    - pip install -r requirements.txt

test:
  image: gitlab.informatik.uni-bremen.de:5005/hoeffner/pandoc-python-docker:latest
  services:
    - docker:dind
  stage: test
  script:
    - echo "Testing..."
    - pytest

deploy_VM:
  stage: deploy_VM
  script:
    - echo "Deploying to VM..."
    - flask run --host=146.169.41.142 >> log.txt 2>61 &

deploy_heroku:
  stage: deploy_heroku
  script:
    - echo "Deploying to Heroku..."
    - dpl --provider=heroku --app=tcr21-simplewebapp --api-key=$HEROKU_API_KEY

