stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - echo "Building...."
    - alias python='/usr/bin/python3'
    - python --version
    - pip3 install -r requirements.txt

test:
  stage: test
  script:
    - echo "Testing..."
    - python3 -m pytest

deploy:
  stage: deploy
  script:
    - echo "Deploying..."
    - python --version
    - python3 --version
    - flask run
