variables:
  HEROKU_API_KEY: $heroku_api_key

stages:
  - build_test
  - deploy_VM
  - deploy_heroku

cache:
  paths:
    - flask_app/

build_test:
  image: python
  stage: build_test
  script:
    - echo "Building...."
    - pip install -r requirements.txt
    - echo "Testing..."
    - pytest

deploy_VM:
  tags: 
    - VM_deployment
  stage: deploy_VM
  script:
    - echo "Deploying to VM..."
    - python3 -m venv flask_app
    - . flask_app/bin/activate
    - pip install -r requirements.txt
    - flask run --host=146.169.41.142 >> log.txt 2>61 &

deploy_heroku:
  image: ruby
  stage: deploy_heroku
  script:
    - echo "Deploying to Heroku..."
    - gem install dpl
    - dpl --provider=heroku --app=tcr21-simplewebapp --api-key=$HEROKU_API_KEY


