stages:
  - build
  - test
  - deploy

cache:
  paths:
    - flask_app/

default:
  tags:
    - shell

build:
  stage: build
  script:
    - echo "Building...."
    - python3 -m venv flask_app
    - . flask_app/bin/activate
    - pip install -r requirements.txt

test:
  stage: test
  script:
    - echo "Testing..."
    - . flask_app/bin/activate
    - pytest

deploy:
  stage: deploy
  script:
    - echo "Deploying..."
    - . flask_app/bin/activate
    - flask run
    - deactivate
