variables:
  HEROKU_API_KEY: $heroku_api_key

.before_script_template:
  before_script:
    - python3 -m venv flask_app 
    - . flask_app/bin/activate
    - pip install -r requirements.txt

stages:
  - build_test
  - deploy_VM
  - deploy_heroku

cache:
  paths:
    - flask_app/

build_test:
  image: python
  stage: build_test
  script:
    - echo "Building...."
    - pip install -r requirements.txt
    - echo "Testing..."
    - pytest

deploy_VM:
  extends: .before_script_template
  tags: 
    - VM_deployment
  stage: deploy_VM
  script:
    - echo "Deploying to VM..."
    - flask run --host=146.169.41.142 >>log.txt 2>&1 &
  artifacts:
    paths: ['log.txt']
    expire_in: 1 week

deploy_heroku:
  extends: .before_script_template
  tags: 
    - Heroku_deployment
  stage: deploy_heroku
  script:
    - echo "Deploying to Heroku..."
    - dpl --provider=heroku --app=tcr21-simplewebapp --api-key=$HEROKU_API_KEY


